spring.application.name=shopsphere-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/shopsphere
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8083
jwt.secret=4f7e9a2b8c1d5e6f9a0b3c7d1e2f4a6b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3
jwt.expiration=600000
